name: Test prod deploy

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy(from build stage)'
        required: true

jobs:
  check-file:
    name: Check file
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.image_tag }}

      - name: Check file
        run: cat test.txt