name: Build simple flask app image
on: push

jobs:
  lint-dockerfile:
    name: Check dockerfile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check file
        run: cat test.txt